# .github/workflows/warmup.yml
name: Cache Warmer

on:
  push:
    branches: [ main ]
  schedule:
    # 工作间隔
    - cron: '0 */8 * * *'   # (每8h工作一次)
  workflow_dispatch:

jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
      - name: Warm up all URLs
        run: |
        
          # 预热url列表
          URLS=(
            "https://blog.cy00.top/"
            "https://blog.cy00.top/privacy/"
            "https://blog.cy00.top/friends/"
            "https://blog.cy00.top/archive/"
            "https://blog2.cy00.top/"
            "https://blog2.cy00.top/privacy/"
            "https://blog2.cy00.top/friends/"
            "https://blog2.cy00.top/archive/"            
          )
          
          for url in "${URLS[@]}"; do
            if [ -n "$url" ]; then
              echo "预热: $url"
              curl -s -o /dev/null -H "User-Agent: Cache-Warmer" "$url" &
            fi
          done
          
          # 预热文章页面
          for i in {1..20}; do
            echo "预热: https://blog.cy00.top/posts/$i/"
            curl -s -o /dev/null "https://blog.cy00.top/posts/$i/" &
            echo "预热: https://blog2.cy00.top/posts/$i/"
            curl -s -o /dev/null "https://blog2.cy00.top/posts/$i/" &
          done          
          
          wait
          echo "完成!"